Linux port
edgarbarney/halflife-planckepoch pull request #28
Opened 2023-05-11 18:40 UTC by a1batross

spirinity very dirty port:
* imgui doesn't hook, and it doesn't load or store video options on Linux
* there is weird bug with BSP faces culling on window edges but the renderer works

2023-05-11 21:21 UTC, edgarbarney requested changes
Sorry, I could do these changes myself but I'm away from a proper computer atm. Can you take a look at the comments? Thanks.

Does this work on Windows too? As I said, I couldn't test it atm :/

I was planning on a safer hook on SDL2, instead of the hw.dll but I don't know how SDL works and I'm not that great on reverse engineering and hooking. The hook implementation is mainly from Half-Payne. So, if you could find a way to do that on Linux, I believe it will work.

I will provide video settings storage but I need to make sure that how video settings are stored in Linux first. I also assume it's a .ini but we'll see.

Also, you replaced all double backslashes with forward slashed? I didn't know we could use them on Windows. I'll try to use them from now on. Thanks.

2023-05-11 21:21 UTC, edgarbarney commented on common/FranUtils.hpp
I think on Linux we can just call [FranUtils::ftol()](https://github.com/edgarbarney/halflife-planckepoch/blob/a6bd84e15b7c8dab6260a1317f7299d0f1dee392/common/FranUtils.hpp#L348) in FranUtils::ftol_asm instead on Linux.

Or should we replace it with FranUtils::ftol() altogether?

Also thanks for removing the asserts. I forgot I left them there.

2023-05-11 21:21 UTC, edgarbarney commented on dlls/extdll.h
I think we can create an uppercase version of the [FranUtils::LowerCase_Ref](https://github.com/edgarbarney/halflife-planckepoch/blob/a6bd84e15b7c8dab6260a1317f7299d0f1dee392/common/FranUtils.hpp#L292) in FranUtils.hpp

2023-05-12 05:36 UTC, a1batross commented on common/FranUtils.hpp
I don't think ftol_asm is needed at all. If you just want type punning, it can be done with union, also competely avoiding issue with strict aliasing.

But I forgot this is C++ and while it's allowed in C99, it's an UB in C++. So this part should be rewritten just to `memcpy`.

2023-05-12 05:36 UTC, a1batross commented on dlls/extdll.h
Yeah, that should more clean.

2023-05-12 05:47 UTC, a1batross commented
>Does this work on Windows too?

I haven't checked it, as I almost never use Windows.
I don't think we should hurry on this, the testing can be done later, after the patchset will be complete. I want to write `hl.conf` parser myself (it's just located in the filesystem root) and try to migrate to SDL2 hooking. We can take some existing DLL export and write the `jmp` there. I saw this technique earlier, but I don't remember which function was hooked, so will figure out myself.

2023-05-13 04:28 UTC, edgarbarney approved these changes

2023-05-13 04:29 UTC, merged

2023-05-22 09:42 UTC, DeafMan1983 commented
Is it already fixed? If it has problem with hooking then you need update for libSDL2 ( bin + dev ) in Linux.